name: Development CI

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Linux Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          pwd
          ls -la
          cd Blaze-web-terminal/
          pm2 list
          pm2 stop 0
          git fetch
          git pull
          npm install
          meteor npm install
          meteor reset
          pm2 start 0
          echo "Deployment completed successfully!"