name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          timeout: 60s
          command_timeout: 15m
          script: |
            set -e
            
            echo "Starting deployment process..."
            
            # Set up environment
            export PATH="$HOME/.meteor:$PATH"
            
            # Define meteor command with fallback
            if command -v meteor >/dev/null 2>&1; then
                METEOR_CMD="meteor"
            else
                METEOR_CMD="$HOME/.meteor/meteor"
            fi
            
            echo "Using Meteor command: $METEOR_CMD"
            $METEOR_CMD --version
            
            # Navigate to project directory
            cd Blaze-web-terminal/
            
            # Check current PM2 status
            echo "Current PM2 processes:"
            pm2 list
            
            # Stop the application
            echo "Stopping application..."
            pm2 stop 0 || echo "Application was not running"
            
            # Update codebase
            echo "Updating codebase..."
            git fetch origin main
            git reset --hard origin/main
            
            # Install dependencies
            echo "Installing Node.js dependencies..."
            npm ci --omit=dev
            
            echo "Installing Meteor dependencies..."
            $METEOR_CMD npm install --omit=dev
            
            # Reset Meteor (only if needed for schema changes)
            echo "Resetting Meteor database..."
            $METEOR_CMD reset
            
            # Start the application
            echo "Starting application..."
            pm2 start 0
            
            # Verify deployment
            echo "Verifying deployment..."
            sleep 5
            pm2 list
            pm2 logs 0 --lines 10
            
            echo "Deployment completed successfully at $(date)"